services:
  ubicor-api:
    build: ubicor-api/

  ubicor-frontend:
    build: 
      context: ubicor-frontend/
      args:
        - BUILD_TIME_API_BASE_URL=${UBICOR_FRONTEND_BUILD_TIME_API_BASE_URL:-http://host.docker.internal:8000}
        - API_BASE_URL=${UBICOR_FRONTEND_API_BASE_URL:-http://api.ubicor.alvarezcristian.com}