version: "3.9"

services:

  reverse-proxy:
    image: traefik:v2.7
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env/.database.env
    volumes:
      - ./scripts/init_database:/docker-entrypoint-initdb.d:ro

  ubicor-api:
    build: ubicor-api/
    labels:
      - "traefik.http.routers.ubicor-api.rule=Host(`api.ubicor.alvarezcristian.com`)"
    ports:
      - "8000:80"
    depends_on:
      - reverse-proxy
      - database
    env_file:
      - .env/.ubicor-api.env

  ubicor-frontend:
    build: 
      context: ubicor-frontend/
      args:
        - API_BASE_URL="ubicor.alvarezcristian.com"
    labels:
      - "traefik.http.routers.ubicor-fronted.rule=Host(`ubicor.alvarezcristian.com`)"
    depends_on:
      - ubicor-api
    ports:
      - "3000:3000"
    env_file:
      - .env/.ubicor-frontend.env
  