version: "3.9"

services:

  reverse-proxy:
    image: traefik:v2.7
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env-services/.database.env
    volumes:
      - ./scripts/init_database:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data

  ubicor-api:
    build: ubicor-api/
    labels:
      - "traefik.http.routers.ubicor-api.rule=Host(`api.ubicor.alvarezcristian.com`)"
    ports:
      - "8000:80"
    depends_on:
      - reverse-proxy
      - database
    env_file:
      - .env-services/.ubicor-api.env

  ubicor-frontend:
    build: 
      context: ubicor-frontend/
      args:
        - BUILD_TIME_API_BASE_URL=http://host.docker.internal:8000
        - API_BASE_URL=${UBICOR_FRONTEND_API_BASE_URL:-http://api.ubicor.alvarezcristian.com}
    labels:
      - "traefik.http.routers.ubicor-frontend.rule=Host(`ubicor.alvarezcristian.com`)"
    depends_on:
      - ubicor-api
    ports:
      - "3000:3000"
    env_file:
      - .env-services/.ubicor-frontend.env

volumes:
  db_data:
