version: "3.9"

services:

  reverse-proxy:
    image: traefik:v2.7
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env-services/.database.env
    volumes:
      - ./scripts/init_database:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data

  backups:
    image: crissalvarezh/automate-backups-to-s3:0.1
    volumes:
      - ubicor-building-images:/backups/static-files/ubicor-building-images
    env_file:
      - .env-services/.backups.env

  ubicor-api:
    image: crissalvarezh/ubicor-api:0.1
    labels:
      - "traefik.http.routers.ubicor-api.rule=Host(`api.ubicor.alvarezcristian.com`)"
    ports:
      - "8000:80"
    depends_on:
      - reverse-proxy
      - database
    volumes:
      - ubicor-building-images:/code/app/static/images/buildings
    env_file:
      - .env-services/.ubicor-api.env

  ubicor-frontend:
    image: crissalvarezh/ubicor-frontend:0.1
    labels:
      - "traefik.http.routers.ubicor-frontend.rule=Host(`ubicor.alvarezcristian.com`)"
    depends_on:
      - ubicor-api
    ports:
      - "3000:3000"
    env_file:
      - .env-services/.ubicor-frontend.env

volumes:
  db_data:
  ubicor-building-images:
