version: "3.9"

services:

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env/.database.env
    volumes:
      - ./scripts/init_database:/docker-entrypoint-initdb.d:ro

  ubicor-api:
    build: ubicor-api/
    depends_on:
      - database
    ports:
      - "8000:80"
    env_file:
      - .env/.ubicor.env
    
  