entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      tlschallenge: true
      email: alvarezhernandezcristian1@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker: {}

log:
  filePath: /traefik.log
  level: ERROR
  format: json
